const stops=[
{name:"West Allis Cheese & Sausage Shoppe",address:"Milwaukee Public Market, 400 N Water St",area:"Historic Third Ward",style:"Fresh, squeaky Wisconsin curds (the benchmark)",note:"Compares retail Wisconsin curd culture with fried curds",lat:43.0352526,lng:-87.9083155,site:"https://milwaukeepublicmarket.org/vendors/west-allis-cheese-sausage-shoppe"},
{name:"Camino",address:"434 S 2nd St",area:"Walker's Point",style:"Deep-fried Clock Shadow Creamery curds with Russian dressing",note:"Crisp exterior, melty interior, local urban cheesemaker",lat:43.0265022,lng:-87.9123333,site:"https://mke.caminomke.com/milwaukee-walkers-point-camino-food-menu"},
{name:"Black Sheep",address:"216 S 2nd St",area:"Walker's Point",style:"Pancake-battered curds with powdered sugar and maple syrup",note:"The sweet-savory wild card stop",lat:43.028949,lng:-87.912312,site:"https://www.blacksheepmke.com/weekend-brunch/"},
{name:"Who's on Third",address:"1007 N Doctor M.L.K. Jr Dr",area:"Westown",style:"Lakefront Riverwest Stein beer-battered curds",note:"Three-sauce flight (house ranch, marinara, Who's Sauce)",lat:43.0431681,lng:-87.9146417,site:"https://whosonthirdmke.com/menu"},
{name:"Milwaukee Brat House",address:"1013 N Doctor M.L.K. Jr Dr",area:"Old World Third St",style:"Classic Wisconsin tavern fried curds",note:"German heritage, brat and curd combo",lat:43.0432973,lng:-87.9149207,site:"https://www.milwaukeebrathouse.com/milwaukee-brat-house-downtown"},
{name:"Lakefront Brewery",address:"1872 N Commerce St",area:"Riverwest / Milwaukee River",style:"Famous brewery beer-battered curds with ranch",note:"Tour finale on the river, rotating limited flavors",lat:43.0547262,lng:-87.9052875,site:"https://lakefrontbrewery.com/beer-hall/curd-of-the-month"}
];
const stopList=document.querySelector('#stop-list');
stops.forEach((s,i)=>{const map=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.name+' '+s.address+' Milwaukee WI')}`;stopList.insertAdjacentHTML('beforeend',`<article class="stop"><div class="stop-num">${String(i+1).padStart(2,'0')}</div><div><p class="neighborhood">${s.area}</p><h3>${s.name}</h3><a href="${map}" target="_blank" rel="noopener">${s.address}, Milwaukee, WI ↗</a></div><div class="style-pill"><span class="style-label">The style</span><p>${s.style}</p><small>${s.note}</small></div><a class="venue-link" href="${s.site}" target="_blank" rel="noopener">Check venue ↗</a></article>`)});
const dates=[];for(let m=7;m<=11;m++){let d=new Date(2026,m,1,12);while(d.getDay()!==6)d.setDate(d.getDate()+1);while(d.getMonth()===m){dates.push(new Date(d));d.setDate(d.getDate()+7)}}
const select=document.querySelector('#tour-date'),status=document.querySelector('#date-status');dates.forEach(d=>{const iso=d.toISOString().slice(0,10),label=d.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'});select.add(new Option(label,iso))});const savedDate=localStorage.getItem('mke-curd-tour-date');if(savedDate){select.value=savedDate;status.textContent=`Locked in: ${select.options[select.selectedIndex].text}`};select.addEventListener('change',()=>{localStorage.setItem('mke-curd-tour-date',select.value);status.textContent=select.value?`Locked in: ${select.options[select.selectedIndex].text}`:'No date selected yet.'});
const map=L.map('map',{scrollWheelZoom:false}).setView([43.0403,-87.9104],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);const marker=(n)=>L.divIcon({className:'',html:`<div class="number-marker" style="width:36px;height:36px">${n}</div>`,iconSize:[36,36],iconAnchor:[18,18]});stops.forEach((s,i)=>L.marker([s.lat,s.lng],{icon:marker(i+1)}).addTo(map).bindPopup(`<h3>${i+1}. ${s.name}</h3><p>${s.style}</p>`));L.polyline(stops.slice(0,3).map(s=>[s.lat,s.lng]),{color:'#df5b2a',weight:5}).addTo(map);L.polyline(stops.slice(2,4).map(s=>[s.lat,s.lng]),{color:'#8f331b',weight:4,dashArray:'8 10'}).addTo(map);L.polyline(stops.slice(3,5).map(s=>[s.lat,s.lng]),{color:'#df5b2a',weight:5}).addTo(map);L.polyline(stops.slice(4).map(s=>[s.lat,s.lng]),{color:'#8f331b',weight:4,dashArray:'8 10'}).addTo(map);map.fitBounds(L.latLngBounds(stops.map(s=>[s.lat,s.lng])),{padding:[35,35]});
const routeOrigin=encodeURIComponent(stops[0].address+', Milwaukee, WI'),dest=encodeURIComponent(stops[5].address+', Milwaukee, WI'),wps=stops.slice(1,5).map(s=>encodeURIComponent(s.address+', Milwaukee, WI')).join('%7C');document.querySelector('#maps-link').href=`https://www.google.com/maps/dir/?api=1&origin=${routeOrigin}&destination=${dest}&waypoints=${wps}&travelmode=walking`;
const scoreRoot=document.querySelector('#scorecards'),metrics=['Crunch','Pull','Seasoning','Sauce','Score'];
const params=new URLSearchParams(location.search);let scores={};
try{scores=JSON.parse(localStorage.getItem('mke-curd-scores')||'{}')}catch(e){}
if(params.has('ratings')){try{scores=JSON.parse(decodeURIComponent(atob(params.get('ratings'))));localStorage.setItem('mke-curd-scores',JSON.stringify(scores));history.replaceState({},'',location.pathname+'#scorecard')}catch(e){}}
function values(d){return metrics.map(m=>Number(d[m.toLowerCase()]||0)).filter(Boolean)}
function average(d){const v=values(d);return v.length?v.reduce((a,b)=>a+b,0)/v.length:0}
function renderScores(){scoreRoot.innerHTML='';stops.forEach((s,i)=>{const data=scores[i]||{};scoreRoot.insertAdjacentHTML('beforeend',`<article class="score-card" data-stop="${i}"><div class="score-head"><div class="badge">${i+1}</div><div><h3>${s.name}</h3><span class="total">${average(data)?average(data).toFixed(1)+' avg':'Not scored'}</span></div></div><div class="metrics">${metrics.map(m=>{const k=m.toLowerCase();return `<div class="metric"><label>${m}<output>${data[k]||'–'}</output></label><div class="rating-buttons" role="group" aria-label="${s.name} ${m} rating">${[1,2,3,4,5,6,7,8,9,10].map(n=>`<button type="button" data-key="${k}" data-value="${n}" class="${Number(data[k])===n?'selected':''}" aria-label="${n} out of 10">${n}</button>`).join('')}</div></div>`}).join('')}</div><div class="score-note"><textarea data-key="note" aria-label="Notes for ${s.name}" placeholder="Tasting notes...">${data.note||''}</textarea></div></article>`)});updateSummary()}
function save(){localStorage.setItem('mke-curd-scores',JSON.stringify(scores));document.querySelector('#save-state').textContent='Saved on this device ✓'}
scoreRoot.addEventListener('click',e=>{const b=e.target.closest('.rating-buttons button');if(!b)return;const card=b.closest('.score-card'),i=card.dataset.stop;scores[i]=scores[i]||{};scores[i][b.dataset.key]=b.dataset.value;save();renderScores()});
scoreRoot.addEventListener('input',e=>{if(e.target.tagName!=='TEXTAREA')return;const i=e.target.closest('.score-card').dataset.stop;scores[i]=scores[i]||{};scores[i].note=e.target.value;save()});
function updateSummary(){const ranked=stops.map((s,i)=>({i,name:s.name,avg:average(scores[i]||{}),count:values(scores[i]||{}).length})).filter(x=>x.count).sort((a,b)=>b.avg-a.avg);const leader=document.querySelector('#leaderboard h3'),list=document.querySelector('#ranking');leader.textContent=ranked.length?`${ranked[0].name} leads at ${ranked[0].avg.toFixed(1)} / 10.`:'Start scoring to crown a curd.';list.innerHTML=ranked.map((x,n)=>`<li><span><b>${n+1}</b> ${x.name}</span><strong>${x.avg.toFixed(1)}</strong></li>`).join('');const all=ranked.flatMap(x=>values(scores[x.i]||{})),overall=all.length?all.reduce((a,b)=>a+b,0)/all.length:0,complete=ranked.filter(x=>x.count===5).length;document.querySelector('#tour-summary').innerHTML=`<p class="eyebrow">Tour-wide summary</p><h3>${overall?overall.toFixed(1)+' / 10 overall':'No stops scored yet.'}</h3><p>${ranked.length} of 6 stops started · ${complete} fully rated · ${all.length} quality ratings saved.</p>`}
function plainSummary(){const ranked=stops.map((s,i)=>({name:s.name,avg:average(scores[i]||{})})).filter(x=>x.avg).sort((a,b)=>b.avg-a.avg);const all=Object.values(scores).flatMap(values),overall=all.length?(all.reduce((a,b)=>a+b,0)/all.length).toFixed(1):'—';return `Milwaukee Cheese Curd Tour 2026\nOverall: ${overall}/10\n${ranked.map((x,i)=>`${i+1}. ${x.name} — ${x.avg.toFixed(1)}/10`).join('\n')}`}
async function copy(text,button){try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent='Copied ✓';setTimeout(()=>button.textContent=old,1600)}catch(e){prompt('Copy this:',text)}}
document.querySelector('#copy-summary').addEventListener('click',e=>copy(plainSummary(),e.currentTarget));
document.querySelector('#share-scores').addEventListener('click',async e=>{const encoded=btoa(encodeURIComponent(JSON.stringify(scores))),url=`${location.origin}${location.pathname}?ratings=${encoded}#scorecard`,text=plainSummary();if(navigator.share){try{await navigator.share({title:'Milwaukee Cheese Curd Tour 2026',text,url});return}catch(err){}}copy(url,e.currentTarget)});
document.querySelector('#reset-scores').addEventListener('click',()=>{if(confirm('Clear every rating and tasting note?')){scores={};localStorage.removeItem('mke-curd-scores');renderScores()}});renderScores();
